all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

    backend:
      hosts:
        api1: 
          ansible_host: 127.0.0.1                            # TODO: replace with real public IP or DNS
          ansible_connection: local
          ansible_user: sasic
